### ISSUE TITLE
JS heap out of memory

### ISSUE THREAD

**Issue by pexxi** [markedjs/marked-mangle#126]
Using marked-mangle exactly as in the instructions causes "JS heap out of memory" error.
I'm running this code in a unit test with Vitest.

New:
```js
import { marked } from "marked";
import { mangle } from "marked-mangle";

...

marked.use(mangle());
const inlineHtml = marked.parse(latestComment);
```

**Comment by UziTech** [comment]
What markdown is in latest comment? If you are running untrusted markdown through marked you should use a [worker](https://marked.js.org/using_advanced#workers) to prevent malicious redos attacks.

**Comment by pexxi** [comment]
Seems like the error occurred if the `marked.use(mangle())` was inside the function that was being called by the unit test instead of being outside the function (being run when the file was imported). Moving this line outside the function fixed the issue, and the output looks correct. 

So, this had to be changed:

```js
import { marked } from "marked";
import { mangle } from "marked-mangle";

export const handler = async () => {
  ...
  marked.use(mangle());
  const inlineHtml = marked.parse(latestComment);
  ...
};

```

to:

```js
import { marked } from "marked";
import { mangle } from "marked-mangle";

marked.use(mangle());

export const handler = async () => {
  ...
  const inlineHtml = marked.parse(latestComment);
  ...
};
```
